title: www.felayman.com
email: felayman@gmail.com
author: felayman
description: felayman个人博客
motto: felayman个人博客
meta_description: felayman个人博客
url: "http://www.felayman.com"
baseurl: ""
github_username:  felayman
gitbook_username: felayman
weibo_username: felayman
weixin_username: felayman
home_url: felayman
github_url: "https://github.com/felayman"
markdown: kramdown
gems: [jekyll-feed,jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: Pygments
permalink: /:categories/:year/:month/:day/:title/
paginate: 10
paginate_path: "home/page:num"

