title: www.felayman.com
email: felayman@gmail.com
author: felayman
description: Actually, less is more!
motto: Actually, less is more!
meta_description: felayman;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
url: "http://www.felayman.com"
baseurl: ""
github_username:  felayman
markdown: kramdown
gems:
  - jekyll-feed
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: Pygments
permalink: /:categories/:year/:month/:day/:title/
paginate: 10
